flowchart TB
    A["using typing somting in the input field"] -- Clicking the save button --> B("sending a post request containing the user input to the server")
    B --> n1["A new note added to the db"]
    n1 --> n2["Redirecting the user to the notes page"]